# Site settings
title: "Rohde & Schwarz VNA Software Page"
email: nick.lalic@rsa.rohde-schwarz.com
description: > # this means to ignore newlines until "baseurl:"
  Applications and software development resources for
  Rohde & Schwarz Vector Network Analyzers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vna.rs-us.net" # the base hostname & protocol for your site
keep_files: [rsatoolbox]
exclude: [Gemfile, Gemfile.lock, 'Miscellaneous info.txt', vagrant, Vagrantfile, readme.md]
# twitter_username: jekyllrb
# github_username:  jekyll

gems:
  - jekyll-minifier

# Build settings
markdown: kramdown

# Organization
sections:
  home:
    title: "Home"
    description: >
      Applications and software development resources for
      Rohde & Schwarz Vector Network Analyzers
    url:   /index.html
  applications:
    title: "Applications"
    description: >
      Ready-to-install VNA applications are provided.
      These utilities extend the capability and convenience of our VNAs.
      New applications are added every few months.
      Feedback and suggestions are welcomed.
    url:   /applications/
  blog:
    title: "Blog"
    description: >
      Answers to common programming questions
    url:   /posts.html
  rsatoolbox:
    title: "C++"
    description: >
      Rsatoolbox is a framework written in C++ and Qt that aims to make
      R&amp;S instrument application development and deployment easier.
      It includes project templates, instrument classes, a Windows installer
      utility, full documentation and more.
    url:   /rsatoolbox.html
  python:
    title: "Python"
    description: >
      Python VNA instrument driver.
    url: /python/
  contact:
    title: "Contact"
    description: >
      For any questions or comments you may have, please see the
      <a href="contact.html">contacts page</a>.
    url:   /contact.html

applications:
  - title: "Cal Unit Control"
    url:   /applications/cal_unit_control.html
  - title: "Display Offsets"
    url:   /applications/display_offsets.html
  - title: "Format Touchstone File"
    url:   /applications/format_touchstone.html
  - title: "IM Spacing Sweep"
    url:   "/applications/im_spacing_sweep.html"
  - title: "Join Cal"
    url:   /applications/join_cal.html
  - title: "PA Compression Test"
    url:   "/applications/pa_compression.html"
  - title: "S2P Extractor"
    url:   /applications/s2p_extractor.html
  - title: "Spectrum Analyzer"
    url:   /applications/spec_an.html
  - title: "TOSM with Autocal"
    url:   /applications/autocal.html
  - title: "User Defined Ports"
    url:   /applications/user_defined_ports.html
  - title: "Verify Cal"
    url:   /applications/verify_cal.html
